### ISSUE TITLE
No options for YFRobot L298P Motor Shield

### ISSUE THREAD

**Issue by petr-kalinin** [DCC-EX/CommandStation-EX#199]
The documentation says (https://dcc-ex.com/reference/hardware/motor-boards.html#yfrobot-l298p-motor-shield) that YFRobot L298P Motor Shield is supported, but also notes that I should "select YFROBOT_MOTOR_SHIELD in your config.h file or from the motor board dropdown if using EX-Installer".

However, in exInstaller I do not have such an option, instead I have Arduino and Polulu shields. 

I've also tried to compile and upload DCC++EX via Arduino IDE, with setting 
```
#define MOTOR_SHIELD_TYPE YFROBOT_MOTOR_SHIELD
```
in `config.h` (although there was no such option in the comment above), and, expectedly, I got error:
```
config.h:29:27: error: 'YFROBOT_MOTOR_SHIELD' was not declared in this scope
```

Is YFRobot L298P Motor Shield supported, and if yes, then do I need any special configuration for it?

**Comment by Ash-4** [comment]
Please check your version number.  The current download from github master is 3.2.0 rc12
The yfrobot board was added fairly recently.  The documentation is being updated in preparation of the next release; not expecting changes from rc12.
github link to download the most recent version:  [https://github.com/DCC-EX/CommandStation-EX/archive/refs/heads/master.zip﻿](https://github.com/DCC-EX/CommandStation-EX/archive/refs/heads/master.zip﻿)
 note that when you extract the files, the name of the directory will need to be renamed to match the .ino file.

Join the discussion on the discord server:  [https://discord.gg/PuPnNMp8Qf﻿](https://discord.gg/PuPnNMp8Qf﻿)
