### ISSUE TITLE
Investigate ONGREEN/ONAMBER/ONRED EX-RAIL commands

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/CommandStation-EX#248]
A recent example of a complex signal suggests adding ONGREEN/ONAMBER/ONRED commands might be a solution to having multiple aspect signals and having one signal trigger behaviour on a remote signal (eg. an approach signal could trigger a distant turnout or siding signal).

**Comment by Asbelos** [comment]
Implemented in PORTX_HAL branch
