### ISSUE TITLE
[To Do]: Validate if native DCC-EX I2C implementation on Nucleo resolves device not detected issue

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/CommandStation-EX#278]
### Task description

With OLED disabled in config.h and the current implementation of I2C for Nucleo which is using the Wire() library, EX-IODetector is unable to be detected on the I2C bus, despite a device at the same address being detected.

When OLED is enabled (even if not connected), this issue goes away.

Need to validate if this is a quirk of the Wire() library by testing again once the native I2C driver for Nucleo is implemented.

**Comment by pmantoine** [comment]
Adding questions I've thought of so we don't lose them from my stoopid brain:

Does the Nucleo hang for a long time probing the I2C when this happens? Are there pullups on the EX-IO board for I2C? What values are they? Does this happen regardless of EX-IO board used... Nano/UNO/Mega etc.?

**Comment by peteGSX** [comment]
This is a non-event. This was actually a bug in the device driver not calling I2CManager.begin(), in addition to a clock speed issue.
