### ISSUE TITLE
[Feature Request]: throttle with output function

### ISSUE THREAD

**Issue by stephane-roux** [DCC-EX/CommandStation-EX#300]
### Problem/idea statement

First, I would like to say bravo for this tools ! 
When I worked on it, I was not stopping saying whaou !

Among all the job you've done, no hurry, but I would like to be able to use a button to manage output in Throttle environment.
I would need a button to run <Z 1 1> and <Z 1 0> (I assume I already prog <Z 1 53 00> for instance)

Idem for web/app and wifi throttle, (but I've to learn Android Studio), you don't manage this Android stuff.

Have a nice time
Thanks again for your huge work
Stef

### Alternatives or workarounds

DCCpp CAB (Spanish Android app), nearly do the job, the best according to me with "Engine Driver".

### Additional context

n/a
If I can help you, translating, testing,...
My config is 
- Arduino Mega with Wifi
- Arduino motorshield
- AT firmware installed like a charm (super tuto)
- IDE installation (compiled without errors, uploaded configuring Arduino Swtiches)
- connecting to WiFi thru internet Box
Working like a charm, I needed 30min to install
\o/

**Comment by habazut** [comment]
If you use the lastest version from devel you can define a route with exrail that will show up as a button in enginedriver. Look for the exrail documentation on our web site.  In exrail you manipulate pin numbers directly (53 in your example).

Harald.

**Comment by habazut** [comment]
Look for the lastest changes in ED doing native DCCEX commands and contact the ED folks for feedback on that.
Harald.

**Comment by flash62au** [comment]
I recommend that you discuss this on the wifi-throttle channel on Discord.
https://discord.gg/PcvucXyY
