### ISSUE TITLE
[Support Request]: analogue loco

### ISSUE THREAD

**Issue by prchal** [DCC-EX/CommandStation-EX#311]
### Version

4.1.2

### Issue description

Can this station control one analogue loco?

**Comment by habazut** [comment]
Analog loco by zero stretching: No and will not be supported.

DC PWM instead of DCC on output: Supported in devel. (use 4.2.14 or later). Planned to be released with next major version.

Harald.

**Comment by prchal** [comment]
Some command reference fo DC? Didn't find any, just EXRAIL SET_TRACK.
