### ISSUE TITLE
v3.0.0 - Release Candidate Feature List

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/CommandStation-EX#33]
### Existing Features ###

- [x] Support Mega, Uno and Nano (some features may not be available on the Uno and Nano)
- [x] Configuration for Arduino Motor Board and Pololu board
- [x] Full Throttle Control &lt;t x x x&gt;
- [x] Turnout Control &lt;T ADDRESS SUBADDRESS THROW&gt;
- [x] Define Turnout &lt;T ADDRESS SUBADDRESS&gt;
- [x] List Defined Turnouts &lt;T&gt;
- [x] Sensor Control
- [x] List Defined Sensors &lt;S&gt;
- [x] Output Control
- [x] List Defined Outputs &lt;Z&gt;
- [x] List Status of all Sensors &lt;Q&gt;
- [x] Accessory Control
- [x] Extended Accessory control with same issue of how to handle listing them
- [x] All CAB functions F0-F28
- [x] Ethernet Shield support
- [x] Throttle reminders
- [x] Store Definitions to EEPROM &lt;E&gt;
- [x] Erase All Definitions from EEPROM &lt;e&gt;
- [x] Display Status &lt;s&gt;

### New features ###

- [x] New waveform generator
- [x] Improved CV read byte
- [x] Improved CV read bit
- [x] Improved CV write byte
- [x] Improved CV write bit
- [x] WiFi Client access to WiThrottle
- [x] Wifi AP access to WiThrottle
- [ ] Extend Turnout Control &lt;T ADDRESS THROW&gt; (no subaddress)
- [ ] Extend Define Turnout &lt;T ADDRESS&gt; (no subaddress)
- [ ] ??? How would we display list defined turnouts if we have two ways to input them?
- [x] Individual track power control
- [x] Ability to join the main and prog tracks to act as one (2 districts?)
- [x] Single or Dual-Pin Inverted PWM output
- [x] New, simpler CAB Fn command
- [x] WiThrottle support
- [x] Function reminders
- [x] Filter / user functions
- [ ] Extended &lt;c&gt; command
- [ ] Extended Accessory Control (1 part addressing in addition to 2 part)
- [x] Diagnostic &lt;D XXX&gt; commands
- [x] Test Multiple Locos
- [x] Test Multiple Throttles
- [x] V Command (verify CV aka validate)

**Comment by grbba** [comment]
If you say Network shield support you include the EthernetShield as well ?

**Comment by FrightRisk** [comment]
Yes, since that has been supported on DCC++ Classic for a while.

**Comment by ldribin** [comment]
This Issue provides the details of what is in CommandStation-EX v3.0.0. and tied to
