### ISSUE TITLE
[Feature Request]: Add a "no programming" option to save RAM on Uno

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/CommandStation-EX#332]
### Problem/idea statement

It would be good to be able to disable all programming functionality to save RAM to allow Uno devices to continue to be used with EXRAIL.

### Alternatives or workarounds

N/A

**Comment by Asbelos** [comment]
Technically this saves very little RAM but has large savings in PEOGMEM which was more the limiting factor.
