### ISSUE TITLE
[To Do]: ARDUINO UNO R4 WIFI

### ISSUE THREAD

**Issue by htmgui** [DCC-EX/CommandStation-EX#341]
### Task description

Please consider adding the new ARDUINO UNO R4 WIFI to the supported microcontrollers.

Thanks.

**Comment by habazut** [comment]
We have discussed the Arduino R4 Wifi but as it is a completely different chip (actually two of them) supporting that would mean a big porting effort. So it is a bit more work than just "add it to the list". With the limitatioins that design has it is doubtful if someone finds it worth doing the work especially if you compare with an ESPduino32 ($5 - $15) for which we will have support in the upcoming 5.0 release and which offers more speed for less cost.

The IDE core library is as new as the chip and it might be strategic to let others find the bugs there first as well.

Harald.
