### ISSUE TITLE
Readme.md has dead link

### ISSUE THREAD

**Issue by deHarro** [DCC-EX/CommandStation-EX#398]
No big deal but annoying for beginners, eager to learn more about the project.

At the end of Readme.md there is a dead link to "rewrite.html".

Citation:
"NOTE: DCC-EX is a major rewrite to the code. We started over and rebuilt it from the ground up! For what that means, you can read [HERE](https://dcc-ex.com/about/rewrite.html)."

Harry

**Comment by flash62au** [comment]
Redirect added for the old page

Peter

**Comment by flash62au** [comment]
Redirect added for the old page

Peter
