### ISSUE TITLE
Help turn I2C Display code into a class

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/CommandStation-EX#40]
To experiment and see how much memory one library for the display uses, I just put code into the config.h and the .ino file. Need help designing a class to pull that out into its own file. Also need to know how to .print() a PROGMEM version. I commented it out and am using a define.

**Comment by davidcutting42** [comment]
@habazut @FrightRisk we finished this, right? Can I close this issue?

**Comment by FrightRisk** [comment]
Completed in version 3.0.0
