### ISSUE TITLE
The response to <s> Request the DCC-EX Version ...  does not match the documentation

### ISSUE THREAD

**Issue by winstanr** [DCC-EX/CommandStation-EX#430]
The separator between the Motor controller type and the build type is documented as /

> Response:
>  <iDCCEX version / microprocessorType / MotorControllerType / buildNumber>
> 

The actual output contains a '-' character 

> <iDCC-EX V-5.0.7 / MEGA / STANDARD_MOTOR_SHIELD G-3bddf4d>

I'm assuming the code is incorrect (as I want to parse the string)

**Comment by Ash-4** [comment]
There have been no code changes in that line in the last 4 years.  The documentation can be updated.
