### ISSUE TITLE
Command Station 3.1 Release Candidate Features

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/CommandStation-EX#66]
### New Features for 3.1 ###

- [x] TPL Automation
- [x] New WiThrottle Integrations
- [x] New JMRI integrations
- [x] Rework accessory <a> command for 1 part linear addressing option
- [x] Create better EEPROM storage format
- [x] Add SDCard support option
- [x] Extended <c> command to provide current in reading, mA and show trip value and max value
- [x] Consisting
- [x] V Command (verify CV aka validate)
- [x] WiFi credentials override and not saved in sketch for security
- [x] Allow DCC accessory messages over PROG track
- [x] Web Throttle onboard the CS
- [x] Diags through WiFi/Ethernet
- [x] Async prog track commands over WiFi/Ethernet
- [x] DIAGs through WiFi/Ethernet
- [x] Turnout processing/Better class (may need a filter to handle WiThrottle integration)
- [x] Turnout names? ex: "coal yard"
- [x] Extended turnout command to handle servo/stepper angle?
- [x] Loop speed detector
- [x] Off board accessory drivers API
- [x] Command to automatically handle long and short writes
- [x] Customizable LCD display
- [x] Use ring buffer to broadcast messages from WiThrottle such as power status, speed, direction, turnout state
- [x] Implement frame rate monitor
- [x] Finalize use of <U> Command
- [x] Add a command to JMRI and the CS to report a list of device capabilities (devCaps structure)
- [x] Add loconet support? (use their throttle)
- [x] Add USB "tether" feature to WiThrottle so we can use a USB cable connection without WiFi
- [x] Turn PROG track into a "booster" so when not in use, it can be a separate power district

### Bus support ###

- [x] evaluate LCC, RF24, MQTT, etc. 

### Installer ###

- [x] Add full cross-platform support
- [x] GUI Enhancements
- [x] Built-In serial monitor
- [x] WiFi support

### WebThrottle-EX

- [x] Save Turnouts (needs new data structure)
- [x] GUI enhancements

### Hardware ###

- [x] Railcom support
- [x] FireBox/FireBit
- [x] Mobile throttle

**Comment by Asbelos** [comment]
Loop Speed and Frame Rate items in list are the same thing I think.
Missing is a performance hike by shortcutting the channel B cycle if power is off. (DONT do this for the A cycle or bad things will happen.)

Does each of the ifeatures need to be on separate cards so that they can be individually discussed/tracked?

**Comment by davidcutting42** [comment]
@Asbelos I think they should be on separate cards. I'll take care of that now.

**Comment by davidcutting42** [comment]
Checking off items as they are moved to separate cards.
