### ISSUE TITLE
Command to automatically handle long and short locoid writes

### ISSUE THREAD

**Issue by powslayer** [DCC-EX/CommandStation-EX#85]
From #66

**Comment by Asbelos** [comment]
Eg command <W 1234> would write locoid 1234 to the loco on prog track and automatically handle the correct cvs and status bits for the long or short form. (The write equivalent of <R>)

**Comment by grbba** [comment]
That is ok for me ( and i implemented that in my RestAPI using basic write commands available ) but poses in general the question about what i would call 'higher order functions' and how to expose them to the user. As an comparison i would say the current JMRI (DCCEX) commands are like Assembler and a function like this is already on an abstraction level like 'C'. So for this type of function should we stick to the Assembler format for exposing them ?

**Comment by Asbelos** [comment]
Reading a cv is already a high order function involving 10 separate conversations with the decoder... reading a cab address is already an 11 to 21 conversation function. It just seems that writing a cab address, at 2..3  conversations  is missing... On 22 Nov 2020 20:40, Gregor Baues <notifications@github.com> wrote:
That is ok for me ( and i implemented that in my RestAPI using basic write commands available ) but poses in general the question about what i would call 'higher order functions' and how to expose them to the user. As an comparison i would say the current JMRI (DCCEX) commands are like Assembler and a function like this is already on an abstraction level like 'C'. So for this type of function should we stick to the Assembler format for exposing them ?

**Comment by Asbelos** [comment]
Remember this should also zero any consist address to avoud confusion.

**Comment by Asbelos** [comment]
ConsistR branch contains this command < W locoid >

**Comment by Asbelos** [comment]
Merged to master 3.0.3
