### ISSUE TITLE
Pre-convert waveform signal pin to DIO2

### ISSUE THREAD

**Issue by Asbelos** [DCC-EX/CommandStation-EX#96]
The pin number to DIO2 register lookup can be performed once at startup rather than every cycle through the interrupt handler.
Less time in ISR means more time for commands etc.

**Comment by FrightRisk** [comment]
Do we have a consensus on this? Is there a PR yet with this in it?

**Comment by Asbelos** [comment]
This should be done also for sensor pins to improve polling loop speed.

**Comment by Asbelos** [comment]
nanoEvery2 branch includes faster signal pins without the DIO2 library.
