### ISSUE TITLE
<+> commands dangerous to locos 

### ISSUE THREAD

**Issue by Asbelos** [DCC-EX/CommandStation-EX#97]
Issuing a wifi control + command is loop blocking and can prevent throttle commands for up to 10 seconds. Could cause an expensive runaway train_off_table incident. 

I suggest that these commands are either  banned with track power on , or cause unilateral track power off.

**Comment by habazut** [comment]
Release 3.0.0 does  turn off track power when issuing a <+> command.

Harald.
